# Generated by Django 6.0 on 2026-01-10 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('vrbo', 'VRBO'), ('other', 'Other')], help_text='Calendar source platform', max_length=50)),
                ('ical_url', models.URLField(help_text='iCal feed URL from external platform', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable calendar sync')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('sync_errors', models.TextField(blank=True, help_text='Last sync error message', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendars', to='api.property')),
            ],
            options={
                'verbose_name_plural': 'External Calendars',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'source')},
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source_booking_id', models.CharField(blank=True, help_text='External booking reference', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the block', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='api.property')),
                ('external_calendar', models.ForeignKey(blank=True, help_text='Source calendar (if from external sync)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='api.externalcalendar')),
            ],
            options={
                'verbose_name_plural': 'Blocked Dates',
                'ordering': ['start_date'],
            },
        ),
    ]
