# Generated by Django 6.0 on 2026-01-27 13:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_externalcalendar_blockeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(default='piece', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when client arrived', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when client departed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='occupancy_status',
            field=models.CharField(default='booked', help_text='Current occupancy state: booked/occupied/departed', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_type', models.CharField(choices=[('no_show', 'Client No-Show'), ('cancellation', 'Client Cancellation'), ('early_checkout', 'Early Checkout'), ('damage', 'Property Damage'), ('refund', 'Refund Request'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.booking')),
            ],
            options={
                'verbose_name_plural': 'Booking Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('initial', 'Initial Stock'), ('restock', 'Restock'), ('assign', 'Assigned to Property'), ('return', 'Returned from Property'), ('client_request', 'Client Request (Extra)'), ('disposed', 'Disposed/Written Off'), ('damaged', 'Damaged'), ('transferred', 'Transferred Between Locations')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField(help_text='Required for audit trail')),
                ('performed_by', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='api.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.inventoryitem')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='api.property')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.location')),
            ],
            options={
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this level')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stock', to='api.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock', to='api.location')),
            ],
            options={
                'verbose_name_plural': 'Location Inventory',
                'ordering': ['location', 'item'],
                'unique_together': {('location', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PropertyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to='api.inventoryitem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.property')),
            ],
            options={
                'verbose_name_plural': 'Property Inventory',
                'ordering': ['property', 'item'],
                'unique_together': {('property', 'item')},
            },
        ),
    ]
