# Generated by Django 6.0 on 2026-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_cancellation_reason_property_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='FCT', max_length=100),
        ),
    ]
