# Generated by Django 6.0 on 2026-01-31 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text="List of permission strings e.g., ['property:read', 'booking:create']")),
                ('is_superuser_role', models.BooleanField(default=False, help_text='If true, this role grants all permissions')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this role is assigned to new users by default')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text="The role that defines this user's permissions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.userrole'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('other', 'Other')], default='other', max_length=20)),
                ('resource_type', models.CharField(help_text='e.g., Property, Booking, User', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('details', models.JSONField(default=dict, help_text='Additional context data (changes, old values, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_act_user_id_ee77c0_idx'), models.Index(fields=['resource_type', '-created_at'], name='account_act_resourc_d707f3_idx'), models.Index(fields=['action', '-created_at'], name='account_act_action_d108a7_idx')],
            },
        ),
    ]
