# Generated by Django 6.0 on 2026-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userrole_customuser_role_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If true, user must change password on next login'),
        ),
    ]
